version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: backend_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_server
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://admin:admin@db:5432/main_db"
    volumes:
      - ./backend:/code
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge

